# Site settings
title: Hundefleisch Ellholz
email: kontakt@hundefleisch-ellholz.de
description: Qualitativ hochwertiges Hundefleisch produziert in Deutschland

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://www.hundefleisch-ellholz.de/" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 

google_analytics: 
addthis_id: 
disqus_account: 

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: envelope
    url: mailto:kontakt@hundefleisch-ellholz.de
  #- title: twitter
  #  url:
  #- title: facebook
  #  url:
  #- title: google-plus
  #  url:
  #- title: github
  #  url: https://github.com/Hundefleisch-Ellholz/hundefleisch-ellholz.de

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
